### PR TITLE
LibLogException - Excluded from code coverage, and internal when LIBLOG_PROVIDERS_ONLY

### LINKED ISSUE #169: Make all types internal
First of all, thanks for the library; it's great to be able to not force users of my library to depend on a logging framework!

Just installed the latest 5.0.0 and I defined `LIBLOG_PROVIDERS_ONLY` to make everything internal (so as not to leak the logging outside of my library), however, `LibLogException` remains public.

Any chance this could be make internal as well if `LIBLOG_PROVIDERS_ONLY` is defined?

Thanks

### LINKED ISSUE #267: LibLogException not being excluded from code coverage
Hi!

So, I'm using LibLog 5.0.6 and when I set the LIBLOG_EXCLUDE_CODE_COVERAGE conditional compile symbol the LibLogException still appears in the code coverage report.

Also, why do we need to use this conditional compilation symbol? I don't see any reason for this not be the default. Does the clients of LibLog want to test LibLog and have the code coverage?
My suggestion would be to inverse the logic and include the attribute by default, and a symbol could control when not to include it, because i'm sure you want to have code coverage for your own tests.

And thanks for this library!

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #169 and resolves #267

### CODE REVIEW

File: src/LibLog/LogProviders/LibLogException.cs [hunk 1]
```diff
@@ -1,11 +1,22 @@
...
+#if !LIBLOG_PROVIDERS_ONLY || LIBLOG_PUBLIC
     /// <summary>
     /// Exception thrown by LibLog.
     /// </summary>
-    public class LibLogException : Exception
+    public
+#else
+    internal
+#endif
+    class LibLogException : Exception
```
Comment (mniak) [inline src/LibLog/LogProviders/LibLogException.cs]: Shouldn't it inherit from `InvalidOperationException`?

Comment (mniak) [reply src/LibLog/LogProviders/LibLogException.cs]: @samcragg, author of #169 suggests that and it seems like a good idea.

Comment (304NotModified) [reply src/LibLog/LogProviders/LibLogException.cs]: IMO the name of the exception (LibLogException) is too general for that. Also this would be a semantic change?

So I think keeping it like this is better.

Comment (snakefoot) [reply src/LibLog/LogProviders/LibLogException.cs]: @mniak Well LibLog is now in palliative care. No need to disturb the patient more than needed.

Comment (mniak) [reply src/LibLog/LogProviders/LibLogException.cs]: No problem. Carry on

**Comment by snakefoot** [comment]
@damianh Any final release of LibLog 5.0.7 RTM in the horizon ?
