### PR TITLE
LibLog - Support dynamic Log4net callerStackBoundaryType 

### LINKED ISSUE #97: LibLog is logging it's own Stack Trace and not the actual log
When I log data in my application and I want the Method Name and Class Name I'm getting the LibLog data and not my application data - Method Name = Log , and Class Name = LoggerExecutionWrapper.

After some debugging it seems that the problem is in the IsInTypeHierarchy method(line 1213) which returns the wrong result so the Stack Trace includes the LibLog data. 
I wrote my own method to check if the types in the Stack Trace are part of the LibLog namespace, if so, I'm creating a new Stack Trace without them.

I'm using LibLog 4.2 + log4net

Thanks

### PR DESCRIPTION
**Pull request by snakefoot**
Reused the trick for NLog callsite (#142) to dynamically resolve log4net stack-boundary-type. Resolves #97 

And also did some minor allocation optimizations.

### CODE REVIEW

**Comment by snakefoot** [comment]
Also fixed the code analysis warnings that have arrives. Resolves #143

File: src/LibLog/LibLog.cs [hunk 1]
```diff
@@ -1393,46 +1448,63 @@ internal class Log4NetLogger
...
+            [SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes")]
             internal Log4NetLogger(dynamic logger)
             {
-                _logger = logger.Logger;
+                try
+                {
+                    _logger = logger.Logger;
+
+                    if (_logEventLevelType == null)
+                        throw new InvalidOperationException("Type log4net.Core.Level was not found.");
```
Comment (damianh) [inline src/LibLog/LibLog.cs]: These exceptions are just getting swallowed below?

**Comment by damianh** [comment]
I appreciate the contribution but I'm having a bit of difficulty parsing and reviewing the PR. There seems to be two different things going on as indicated by the two commits. The first one is the Code Analysis suppression (issue #143) and the other is the resolving log4net stack-boundary-type.  Could you kindly split this into separate PRs? Note, there have been quite a few changes in #149 , I suggest target that branch instead.

I can see that having everything in one file is problematic for PRs. It looks like with the new build SDK way of doing things I'll be able to split it up as it'll be hidden from the consumer.

File: src/LibLog/LibLog.cs (hunk 1 above)
Comment (snakefoot) [reply src/LibLog/LibLog.cs]: Yes it is mostly about making people aware, that something is not working. Since throwing exceptions in the static-constructor is not recommended.

**Comment by snakefoot** [comment]
I will revert the code-analysis part, and just do the log4net. Then code-analysis will be a separate PR

**Comment by damianh** [comment]
The code analysis bit needs a bit more thought because of what the intention is - failing fast and hard if the reflection stuff suddenly stops working if one of the framework dependencies are updated. 

Might have to reconsider how to approach that.

**Comment by snakefoot** [comment]
> Might have to reconsider how to approach that.

Usually logging libraries try not to take down the entire application, when something is configured wrong. Usually it is detected by nothing is logged.

**Comment by wexman** [comment]
Any news here? this is the only issue keeping me from switching to LibLog...

**Comment by snakefoot** [comment]
@damianh Added support for NLog ver, 4.5 RTM that supports structured templates without additional help.

**Comment by damianh** [comment]
Thx for PR!

Slow response due to other commitments of time, sorry.
